# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to=main.models.get_path, verbose_name='Child photo')),
                ('name', models.CharField(max_length=128, verbose_name='Child name')),
                ('gender', models.CharField(choices=[('B', 'BOY'), ('G', 'GIRL')], default='G', max_length=1, verbose_name='Child gender')),
                ('birthday', models.DateField(verbose_name='Child birthday')),
                ('classroom', models.CharField(choices=[('CLASS_1', 'Class one'), ('CLASS_2', 'Class two'), ('CLASS_3', 'Class three')], default='CLASS_1', max_length=7, verbose_name='Child class')),
                ('learn', models.BooleanField(default=False, verbose_name='Learn')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bring_time', models.DateTimeField(verbose_name='Time when bring child to childhood')),
                ('pick_up_time', models.DateTimeField(blank=True, null=True, verbose_name='Time when pick up child from childhood')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='main.Child', verbose_name='Child')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother', models.CharField(max_length=128, verbose_name='Mother name')),
                ('father', models.CharField(max_length=128, verbose_name='Father name')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='main.Child', verbose_name='Parents')),
            ],
        ),
    ]
